# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reconstructCoinbase <- function(source, extract_only) {
    .Call(`_oberon_reconstructCoinbase`, source, extract_only)
}

reconstructBitstamp <- function(quotes, trades, extract_only) {
    .Call(`_oberon_reconstructBitstamp`, quotes, trades, extract_only)
}

reconstructBitfinex <- function(quotes, trades, extract_only) {
    .Call(`_oberon_reconstructBitfinex`, quotes, trades, extract_only)
}

events2image <- function(events, min_price, max_price, tick_size, start, end, sampling_period) {
    .Call(`_oberon_events2image`, events, min_price, max_price, tick_size, start, end, sampling_period)
}

obtainCoinbase <- function(product, file_name) {
    invisible(.Call(`_oberon_obtainCoinbase`, product, file_name))
}

