# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reconstructCoinbase <- function(source, extract_only) {
    .Call(`_oberon_reconstructCoinbase`, source, extract_only)
}

reconstructBitstamp <- function(quotes, trades, extract_only) {
    .Call(`_oberon_reconstructBitstamp`, quotes, trades, extract_only)
}

reconstructBitfinex <- function(quotes, trades, extract_only) {
    .Call(`_oberon_reconstructBitfinex`, quotes, trades, extract_only)
}

